---
- name: JenkinsPlaybook
  hosts: jenkinshosts
  become: true
  remote_user: root
  gather_facts: true
  vars_files:
    - ./vars/main.yml
  roles:
    - role: base
    - role: add_users
    - role: sysctl
    - role: nginx
    - role: docker
    - role: vhost_docker_add
    - role: dock_jenkins_deploy
  environment: "{{ proxy_env }}"
